Project: athena
Version: "0.0.1"

GENERAL:
    # Applications:
    #               99 - Spam mail filter
    APPLICATION: 0

    # Log levels: 0 - LOG_FATAL
    #             1 - LOG_ERROR
    #              2 - LOG_INFO
    #              3 - LOG_DEBUG
    LOG_LEVEL: 2

    # Format of gauge file
    GAUGE_FILE_FORMAT: csv

    # Model selector, crossval idation is default
    ENABLE_MODEL_SELECTOR: true

    # Maximum allowed number of to-be-trained models
    MAX_NUM_MODELS: 3

    # Minimum number of product models
    MIN_NUM_MODELS: 2

# Machine-learning engine

ML_ENGINE_CORE:
    # Machine-learning engine type:
    # 0 - support vector machine (SVM)
    # 1 - decision tree (DCT)
    # 2 - random forest
    # 3 - DNN
    ENGINE_CORE_TYPE: 0
    SVM:
        # rbf, linear, poly, sigmoid, precomputed
        KERNEL: rbf
        C: 100.
        GAMMA: auto
        # used by poly & sigmoid
        COEF0: 0.
        # only used by poly
        DEGREE: 3
    DCT:
        MIN_SAMPLE_SPLIT: 10
        # gini or entropy
        CRITERION: entropy
    RMF: # Random Forest
        MIN_SAMPLES_SPLIT: 2
        N_ESTIMATORS: 10
        CRITERION: entropy
    DNN:
        EPOCHS: 1000
        NEURONS: :[10,20,10]
        ACTIVATION: ['relu','relu','relu']
        DROPOUT_RATE: [0.2,0.2,0.2]
        BATCH_SIZE: 100
        ALGORITHM: SGD
        WEIGHT_INIT: uniform
        LEARN_RATE: 0.01
        MOMENTUM: 0.1 #ONLY USED WHEN ALGORITHM == SGD

FEATURE_EXTRACTOR:
    # Type of feature extractor:
    # 99 - word count
    EXTRACTOR_TVPE: 0

MODEL_SELECTOR:
    # number of groups in which the train data is divided for cross-validation
    CV_FOLD: 5
    # number of threads running in parallel
    N_JOBS: 8
########################### Classifiers ###########################
    MODEL_1:
        ENABLED: false
        MODEL_NAME: SVM
        KERNEL_LIST: [rbf,sigmoid]
    MODEL_2:
        ENABLED: false
        MODEL_NAME: DCT # Decision tree
        SAMPLE_SPLIT: 4,200,100 # min,max,num
    MODEL_3:
        ENABLED: false
        MODEL_NAME: RMF # Random forest
        N_ESTIMATORS: 10,200,10 # min,max,num
        CRITERION: [gini,entropy]
        MIN_SAMPLES_SPLIT: 2,40,10
    MODEL_4:
        ENABLED: false
        MODEL_NAME: DNN
        
        RANDOM_SEED: -1 # -1 means no seed
        NEURONS: [10,20,10]
        ACTIVATION: ['softmax','softplus','softsign','relu','tanh','sigmoid','hard_sigmoid','linear']
        EPOCHS: 100,1000,10 # START,STOP,NUM
        BATCH_SIZE: 10,200,10
        DROPOUT_RATE: 0.0,0.9,10
        ALGORITHM: ['SGD','RMSprop','Adagrad','Adadelta','Adam','Adamax','Nadam']
        WEIGHT_INIT: ['uniform','lecun_uniform','normal','zero','glorot_normal','glorot_uniform','he_normal','he_uniform']
        LEARN_RATE: 0.001,0.3,10
        MOMENTUM: 0.,0.9,10 #ONLY USED WHEN ALGORITHM == SGD
        
########################### App config starts here ###########################
FTS: # Forex Tick Sampler
    TICK_FILE: EURUSD_201810010001_201810030127.csv
    TAKE_PROFIT_POINTS: 100 
    STOP_LOSS_POINTS: 100
    FOREX_SYMBOL: EURUSD

